/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlocksIndexRouteImport } from './routes/blocks.index'
import { Route as TransactionsIdRouteImport } from './routes/transactions.$id'
import { Route as BlocksHeightRouteImport } from './routes/blocks.$height'
import { Route as AddressPubkeyRouteImport } from './routes/address.$pubkey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksIndexRoute = BlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksHeightRoute = BlocksHeightRouteImport.update({
  id: '/blocks/$height',
  path: '/blocks/$height',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressPubkeyRoute = AddressPubkeyRouteImport.update({
  id: '/address/$pubkey',
  path: '/address/$pubkey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/address/$pubkey': typeof AddressPubkeyRoute
  '/blocks/$height': typeof BlocksHeightRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/blocks': typeof BlocksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/address/$pubkey': typeof AddressPubkeyRoute
  '/blocks/$height': typeof BlocksHeightRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/blocks': typeof BlocksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/address/$pubkey': typeof AddressPubkeyRoute
  '/blocks/$height': typeof BlocksHeightRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/blocks/': typeof BlocksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/address/$pubkey'
    | '/blocks/$height'
    | '/transactions/$id'
    | '/blocks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/address/$pubkey'
    | '/blocks/$height'
    | '/transactions/$id'
    | '/blocks'
  id:
    | '__root__'
    | '/'
    | '/address/$pubkey'
    | '/blocks/$height'
    | '/transactions/$id'
    | '/blocks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressPubkeyRoute: typeof AddressPubkeyRoute
  BlocksHeightRoute: typeof BlocksHeightRoute
  TransactionsIdRoute: typeof TransactionsIdRoute
  BlocksIndexRoute: typeof BlocksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/$height': {
      id: '/blocks/$height'
      path: '/blocks/$height'
      fullPath: '/blocks/$height'
      preLoaderRoute: typeof BlocksHeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/address/$pubkey': {
      id: '/address/$pubkey'
      path: '/address/$pubkey'
      fullPath: '/address/$pubkey'
      preLoaderRoute: typeof AddressPubkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressPubkeyRoute: AddressPubkeyRoute,
  BlocksHeightRoute: BlocksHeightRoute,
  TransactionsIdRoute: TransactionsIdRoute,
  BlocksIndexRoute: BlocksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
